### ISSUE TITLE
[TypeError] integration with vuex:  Cannot read property 'initComponent' of undefined

### ISSUE THREAD

**Issue by AngusFu** [Scandltd/vue-injector#25]
**Describe the bug**

I want to add vue-injector to my project, which is using `vue`+`vuex`+`vue-router`.

But I just got errors: 

```
[Vue warn]: Error in beforeCreate hook: "TypeError: Cannot read property 'initComponent' of undefined"
```

Seems those `new Vue(/*...*/)`  instantiations in `vuex` caused all these errors.

**To Reproduce**

Open the demo on [codesandbox](https://codesandbox.io/s/nwl6w4v38p)

**Expected behavior**

No errors.

**Screenshots**

![image](https://user-images.githubusercontent.com/8180186/51428210-ef99e800-1c3b-11e9-9f1d-a87247f04932.png)

**Comment by stelitsyn-sc** [comment]
@AngusFu https://vue-injector.netlify.com/guide/essentials/vuex.html
Registration of global services has also changed:

```
new VueInjector({ store, root: [AnyService] });
```

**Comment by AngusFu** [comment]
Great 👍
