### ISSUE TITLE
Vue 3 & Class Component - @Inject does not work, Service is undefined

### ISSUE THREAD

**Issue by LukasWillin** [Scandltd/vue-injector#88]
### **Describe the bug**
Vue3 `@Inject` does not work.
We tried `@Inject httpClient!: HttpClient;` and `Inject(HttpClient) httpClient!: HttpClient;`
**It works** when using the `this.httpClient = this.$injector.get(HttpClient);` or via `providers { httpClient: HttpClient }`.
So the whole Framework should be set up correctly.

### **To Reproduce**
1. Create a standard project with Vue3 and Typescript via the VueCLI.
2. Create a service.
3. Create a component.
4. Try to inject the service into the compoent with @Inject

### **Expected behavior**
Service is available in Component (Not undefined)

### **Sources**
Some extracted code to visualize the use case
```json
// package.json
{
  "name": "webapp",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@scandltd/vue-injector": "^4.0.2",
    "axios": "^0.21.4",
    "bootstrap": "^5.1.1",
    "core-js": "^3.17.3",
    "vue": "^3.0.0",
    "vue-class-component": "^8.0.0-0",
    "vue-good-table": "^2.21.10",
    "vue-router": "^4.0.0-0"
  },
  "devDependencies": {
    "@babel/plugin-proposal-decorators": "^7.15.4",
    "@typescript-eslint/eslint-plugin": "^4.18.0",
    "@typescript-eslint/parser": "^4.18.0",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-typescript": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "@vue/eslint-config-typescript": "^7.0.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0",
    "typescript": "~4.1.5"
  }
}
```

```json
// tsconfig.json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "baseUrl": ".",
    "types": [
      "webpack-env"
    ],
    "paths": {
      "@/*": [
        "src/*"
      ]
    },
    "lib": [
      "esnext",
      "dom",
      "dom.iterable",
      "scripthost"
    ]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "tests/**/*.ts",
    "tests/**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

```ts
// main.ts
import 'core-js/features/reflect';
import 'core-js/features/promise';
import 'core-js/features/map';

import { createApp } from 'vue'
import App from './App.vue'
import router from './router'
import 'bootstrap/dist/css/bootstrap.min.css';
import 'vue-good-table/dist/vue-good-table.css';
import plugin from '@scandltd/vue-injector';

createApp(App)
    .use(router)
    .use(plugin)
    .mount('#app')
```

```ts
// HttpClient
import { Injectable } from '@scandltd/vue-injector'

@Injectable
export default class HttpClient{ ... }
```

```ts
// Login Form
import { Vue, Options} from 'vue-class-component';
import { Injectable, Inject } from '@scandltd/vue-injector';
import HttpClient from '@/service/network/HttpClient';

@Options({})
@Injectable
export default class FormLogin extends Vue 
{
    private userLoginRequestDto: UserLoginRequestDto = new UserLoginRequestDto();
    @Inject(HttpClient) httpClient!: HttpClient;

    private onLoginClick(): void
    { 
      this.httpClient.post<AuthenticationResponseDto>("application/authenticate", this.userLoginRequestDto)
          .then(auth => {
               this.$router.push("clients");
          });
     }
}
```

### **Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome 93.0.4577.63 (Official Build) (64-Bit), Firefox 92.0 (64-Bit)

Can you give me any pointers? Or is this feature simply not yet implemented for Vue 3?

**Comment by stelitsyn-sc** [comment]
@LukasWillin thanks for your participation. Please update the package to the latest version with the next tag and let me know if the issue persists

**Comment by LukasWillin** [comment]
@stelitsyn-sc Thank you very much! I'll check it out today and give feedback!

**Comment by LukasWillin** [comment]
The @Inject decorator works like a charm!

Something else I noticed however I don't think it's an issue and probably expected.
Behaviour of @Injectable seems to have changed. I originally thought it's needed on the Vue Classes in order to be able to @Inject which is why I left them there at first. This is not the case. However the vue-cli build would now throw:
```
Unable to resolve signature of class decorator when called as an expression.
  Type 'InjectableConstructor<any>' is missing the following properties from type 'typeof Workstations': registerHooks, with
    17 | import Column from '@/types/Table/Column';
    18 |
  > 19 | @Injectable
       | ^^^^^^^^^^^
    20 | @Options({
    21 |     providers: {
    22 |         httpClient: HttpClient
```
After removing the @Injectable from the Vue class everything worked as expected.

In hindsight it makes sense but it wasn't immediately clear to me by looking at the examples.

Regards Lukas

**Comment by stelitsyn-sc** [comment]
@LukasWillin you should use `@Injectable` only for services that you going to inject in the future. You got this error because this decorator add the `injectable` type for each service, but Vue expects a component. 

 We've added a new [example for typescript](https://github.com/Scandltd/vue-injector/tree/master/examples)
